PrimeFaces.locales['th'] = {
	closeText : 'ปิด',
	prevText : 'เดือนย้อนหลัง',
	nextText : 'เดือนถัดไป',
	currentText : 'วันปัจจุบัน',
	monthNames : [ 'มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน',
			'กรกฏาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม' ],
	monthNamesShort : [ 'ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.',
			'ก.ย.', 'ตุ.ค.', 'พ.ย.', 'ธ.ค.' ],
	dayNames : [ 'Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma',
			'Cumartesi' ],
	dayNamesShort : [ 'Pz', 'Pt', 'Sa', 'Ça', 'Pe', 'Cu', 'Ct' ],
	dayNamesMin : [ 'Pz', 'Pt', 'Sa', 'Ça', 'Pe', 'Cu', 'Ct' ],
	weekHeader : 'Hf',
	firstDay : 1,
	isRTL : false,
	isBE:true,
	autoConversionField:true,
	showMonthAfterYear : false,
	yearSuffix : '',
	timeOnlyTitle : 'Zaman Seçiniz',
	timeText : 'Zaman',
	hourText : 'Saat',
	minuteText : 'Dakika',
	secondText : 'Saniye',
	ampm : false,
	month : 'เดือน',
	week : 'สัปดาห์',
	day : 'วัน',
	allDayText : 'Tüm Gün'
};